### ISSUE TITLE
Можно как то на ориг сборке так-же сделать модель дробовика с олдед хомиграда? я пытался но оружие в фэйке летало сверху рук, и прицел был сломан

### ISSUE THREAD

**Issue by Figachi** [magmen3/OpenGrad#2]

**Comment by magmen3** [comment]
ээ там в файлах фейка (точно не помню каких, вроде fakegunent только) нужно менять позиции модельке чтобы в фейке нормально все было

**Comment by Figachi** [comment]
можешь сам файл с фиксом прицела скинуть?

**Comment by Figachi** [comment]
если есть

**Comment by Figachi** [comment]
можно со сборки опенграда просто я не знаю какие от-туда взять надо файлы

**Comment by magmen3** [comment]
сделай сам епта там даже луа знать ненадо

**Comment by Figachi** [comment]
я нигде не нашёл этих файлов чтоб код менять

**Comment by Figachi** [comment]
+ надо знать луа

**Comment by Figachi** [comment]
и я вообще где найду эти луа что-бы что-то менять?

**Comment by Figachi** [comment]
луашку как исправить прицел я нашёл, но я не знаю как фикснуть положение камеры при прицеле

**Comment by Figachi** [comment]
луашку как фиксануть положение при фэйке я нашёл но там нихера не понятно

**Comment by Figachi** [comment]
скопировал с твоего кода, теперь можешь сказать как поменять положение камеры при прицеле?

**Comment by Figachi** [comment]
кста, если что ссылка на дс опенграда не работает
